version: '2'

services:
    python:
        build: ./Python
        container_name: python
        depends_on: 
            - influxdb-grafana
        volumes:
            - .:/repo
    
    influxdb-grafana:
        image: philhawthorne/docker-influxdb-grafana
        container_name: influxdb-grafana
        ports:
            - 3003:3003
            - 8086:8086
            - 3004:8083
        volumes:
            - ./Database/influxdb:/var/lib/influxdb
            - ./Database/grafana:/var/lib/grafana